services:
 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend-dev:
    image: backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/backend
    profiles:
      - backend
    ports:
      - 3001:3001
    container_name: backend-dev
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/database